default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= Rails.application.credentials.Database_Development[:Password] %>
  host: 127.0.0.1

development:
  <<: *default
  database: Personal_Coordinator

# test:
#   <<: *default
#   database: Personal_Coordinator_test

production:
  <<: *default
  database: Personal_Coordinator
  username: root
  password: <%= Rails.application.credentials.Database_Production[:Password] %>
  host: <%= Rails.application.credentials.Database_Production[:Host] %>
